<?php

namespace App\Models;

use Session;

class Guest extends Customer
{
    protected $table = 'customers';

    protected $attributes = [
        'first_name' => 'Guest',
        'last_name' => 'User',
    ];

    public function __construct()
    {
        parent::__construct();
        //echo 'Loading session';
        //pr($this->attributes);
        $this->attributes = array_merge($this->attributes, Session::get('guest', []));
        //pr($this->attributes);
    }


    public function create(array $attributes = [])
    {
        return null;
    }

    public function __set($key, $value)
    {
        parent::__set($key, $value); // TODO: Change the autogenerated stub
        $this->save();
    }

    public function getAttribute($key)
    {
        $data = Session::get('guest');
        return array_get($data, $key, parent::getAttribute($key));
    }

    public function setAttribute($key, $value)
    {
        //pr('setting attribute', $key, $value);
        parent::setAttribute($key, $value);
        $this->save();
    }

    public function save(array $options = [])
    {
        $this->attributes = array_merge($this->attributes, $options);
        //pr('saving session', $this->attributes);
        Session::put('guest', $this->attributes);
        return true;
    }

}
